{{- if (include "rocketmq.broker.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketmq.broker.configMapName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "common.tplvalues.render" ( dict "value" .Values.broker.configuration "context" $ ) | nindent 4 }}
{{- end -}}