{{- if (include "rocketmq.broker.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketmq.broker.configMapName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  broker.conf: |
    storePathRootDir={{ .Values.broker.storePathRootDir }}
    initAuthenticationUser={"username": "{{ .Values.broker.superUser.username }}","password": "{{ .Values.broker.superUser.password }}"}
    {{- include "common.tplvalues.render" ( dict "value" .Values.broker.configuration "context" $ ) | nindent 4 }}
  tools.yml: |
    accessKey: {{ .Values.broker.superUser.username }}
    secretKey: {{ .Values.broker.superUser.password }}
{{- end -}}