apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.broker.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
  {{- if or .Values.broker.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.broker.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.broker.service.type }}
  {{- if and .Values.broker.service.clusterIP (eq .Values.broker.service.type "ClusterIP") }}
  clusterIP: {{ .Values.broker.service.clusterIP }}
  {{- end }}
  {{- if .Values.broker.service.sessionAffinity }}
  sessionAffinity: {{ .Values.broker.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.broker.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.broker.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.broker.service.type "LoadBalancer") (eq .Values.broker.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.broker.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.broker.service.type "LoadBalancer") (not (empty .Values.broker.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{- toYaml .Values.broker.service.loadBalancerSourceRanges | nindent 4}}
  {{- end }}
  {{- if and (eq .Values.broker.service.type "LoadBalancer") (not (empty .Values.broker.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.broker.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: broker
      port: {{ .Values.broker.service.ports.broker }}
      protocol: TCP
      targetPort: broker
      {{- if (and (or (eq .Values.broker.service.type "NodePort") (eq .Values.broker.service.type "LoadBalancer")) .Values.broker.service.nodePorts.broker) }}
      nodePort: {{ .Values.broker.service.nodePorts.broker }}
      {{- else if eq .Values.broker.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: ha
      port: {{ .Values.broker.service.ports.ha }}
      protocol: TCP
      targetPort: ha
      {{- if (and (or (eq .Values.broker.service.type "NodePort") (eq .Values.broker.service.type "LoadBalancer")) .Values.broker.service.nodePorts.broker) }}
      nodePort: {{ include "rocketmq.broker.haListenPort" . }}
      {{- else if eq .Values.broker.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: fast
      port: {{ .Values.broker.service.ports.fast }}
      protocol: TCP
      targetPort: fast
      {{- if (and (or (eq .Values.broker.service.type "NodePort") (eq .Values.broker.service.type "LoadBalancer")) .Values.broker.service.nodePorts.broker) }}
      nodePort: {{ include "rocketmq.broker.fastListenPort" . }}
      {{- else if eq .Values.broker.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.broker.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.broker.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.broker.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
