apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.broker.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
  {{- if or .Values.broker.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.broker.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.namesrv.service.type }}
  ports:
    - name: broker
      port: 10911
      protocol: TCP
      targetPort: broker
      {{- if (or (eq .Values.namesrv.service.type "NodePort") (eq .Values.namesrv.service.type "LoadBalancer")) }}
      nodePort: {{ include "rocketmq.broker.listenPort" . }}
      {{- end }}
    - name: ha
      port: 10909
      protocol: TCP
      targetPort: ha
      {{- if (or (eq .Values.namesrv.service.type "NodePort") (eq .Values.namesrv.service.type "LoadBalancer")) }}
      nodePort: {{ include "rocketmq.broker.haListenPort" . }}
      {{- end }}
    - name: fast
      port: 10912
      protocol: TCP
      targetPort: fast
      {{- if (or (eq .Values.namesrv.service.type "NodePort") (eq .Values.namesrv.service.type "LoadBalancer")) }}
      nodePort: {{ include "rocketmq.broker.fastListenPort" . }}
      {{- end }}
    {{- if .Values.broker.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.broker.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.broker.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
