annotations:
  category: Infrastructure
apiVersion: v2
name: mosquitto
type: application
version: 1.0.0
appVersion: 2.0.18
description: Eclipse Mosquitto is an open source (EPL/EDL licensed) message broker that implements the MQTT protocol versions 5.0, 3.1.1 and 3.1. Mosquitto is lightweight and is suitable for use on all devices from low power single board computers to full servers
icon: https://djeqr6to3dedg.cloudfront.net/repo-logos/library/eclipse-mosquitto/live/logo.png
home: https://mosquitto.org/
sources:
- https://github.com/eclipse/mosquitto
dependencies:
- name: common
  version: 2.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
