auth:
  enabled: true
  type: nacos
  server:
    identityKey: su7
    identityValue: AreYouOk
  token:
    cacheEnabled: false
    expireSeconds: 1800
    value: |-
      Q1hkWkd4QnpiSlQwM3NxdmVtTnVVaTRWbGNBUndhT0trcExIODFZbzlXMnQ1Z01oU1FGNmZ5cklERWpuUDdyaw==

