global:
  storageClass: "longhorn"

diagnosticMode:
  enabled: false

console:
  ingress:
    hostname: "test.eastcoal.club"
    tls: false

mysql:
  rootPassword: "123456"

sidecar:
  externalLibraries:
  - url: "https://git.eastcoal.club/api/v4/projects/70/repository/files/lib%2Fsidecar.zip/raw?ref=master"
    args: ["--header", "\"PRIVATE-TOKEN: mvKFuz5WV8n2DirbSSMN\""]
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false

