apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: console
  name: console-outer
  namespace: cloudcanal
spec:
  type: NodePort
  ports:
    - name: "31111"
      port: 8111
      targetPort: 8111
      nodePort: 31111
  selector:
    cloudcanal-service: console
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: console
  name: console
  namespace: cloudcanal
spec:
  ports:
    - name: "7007"
      port: 7007
      targetPort: 7007
    - name: "8084"
      port: 8084
      targetPort: 8084
    - name: "8111"
      port: 8111
      targetPort: 8111
  selector:
    cloudcanal-service: console
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  namespace: cloudcanal
data:
  business-output.properties: |
    ############################################
    ## [BASIC,must have] core port config     ##
    ############################################
    server.port=8111
    cloudcanal.rsocket.console.port=7007
    sidecar.config.prometheus.pull.port=8085
    console.config.prometheus.pull.port=8084
    clougence.rdp.console.enable_product_cluster=true
    ############################################
    ## [BASIC,must have] core database config ##
    ############################################
    spring.datasource-cc.url=jdbc:mysql://mysql:3306/cloudcanal_console?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&socketTimeout=30000&connectTimeout=3000
    spring.datasource-cc.username=root
    spring.datasource-cc.password=123456

    spring.datasource-rdp.url=jdbc:mysql://mysql:3306/clougence_rdp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&socketTimeout=30000&connectTimeout=3000
    spring.datasource-rdp.username=root
    spring.datasource-rdp.password=123456
    #############################################
    ## [BASIC,must have] login security config ##
    #############################################
    jwt.secret=ljgefdgjosdighjeroigh
    ##################################################
    ## [BASIC,must have] console communication host ##
    ##################################################
    console.rsocket.dns=console
    console.config.rsocket.connect_timeout_ms=10000
    console.config.rsocket.wait_result_timeout_ms=300000
    console.config.metadata.fetch.socket_timeout_ms=60000
    #################################
    ## dingding group alert config ##
    #################################
    # console.config.alert.type=dingtalk
    # console.config.alert.dingtalk.alerturl=
    # console.config.alert.dingtalk.timeout=5000
    # console.config.alert.weixin.alerturl=
    # console.config.alert.slack.alerturl=
    # console.config.alert.discord.alerturl=
    # console.config.alert.feishu.alerturl=
    # console.config.alert.custom.alerturl=

    clougence.rdp.alert.type=dingtalk
    clougence.rdp.alert.dingtalk.alerturl=
    clougence.rdp.alert.weixin.alerturl=
    clougence.rdp.alert.slack.alerturl=
    clougence.rdp.alert.discord.alerturl=
    clougence.rdp.alert.feishu.alerturl=
    clougence.rdp.alert.custom.alerturl=
    clougence.rdp.alert.timeout.ms=5000

    console.config.alert.incre.delay.scan.period.sec=300
    console.config.alert.task.indicator.suppression.min=1
    #######################
    ## mail alert config ##
    #######################
    spring.mail.host=
    spring.mail.port=
    spring.mail.username=
    spring.mail.password=
    spring.mail.properties.from=
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    spring.mail.properties.mail.smtp.starttls.required=true
    spring.mail.properties.mail.smtp.ssl.enable=true
    spring.mail.properties.mail.transport.protocol=smtps
    ############################
    ## monitor service config ##
    ############################
    prometheus.host=http://prometheus:9090
    ######################
    ## install  config  ##
    ######################
    clougence.rdp.product.trial=true
    #console.config.product.trial=true
    clougence.rdp.install.oss.ak=
    clougence.rdp.install.oss.sk=
    #console.config.install.oss.ak=
    #console.config.install.oss.sk=
    console.config.install.oss.download_site=
    console.config.install.oss.download_region=hangzhou
    clougence.rdp.install.oss.special=false
    clougence.rdp.install.oss.special.endpoint=
    clougence.rdp.install.oss.special.bucket=
    #console.config.install.oss.special=false
    #console.config.install.oss.special.endpoint=
    #console.config.install.oss.special.bucket=
    console.config.install.http.package=
    console.config.package.mode=K8S
    #################################################
    ## aliyun sms authed access key and secret key ##
    #################################################
    clougence.rdp.sms.verify_code=true
    clougence.rdp.sms.aliyun.ak=
    clougence.rdp.sms.aliyun.sk=
    #console.config.send.alert.ak=
    #console.config.send.alert.sk=
    #####################
    ## aliyun vpc info ##
    #####################
    clougence.rdp.api.aliyun.invpc=false
    #console.config.api.aliyun.invpc=false
    #####################
    ## other           ##
    #####################
    console.config.task.ddlsync.default=false
    #console.config.api.aliyun.privateinfo.clean=false
    console.config.cross.origins=*
    #####################
    ## function limit  ##
    #####################
    #console.config.task.crteated.limited=false
    #console.config.task.crteated.limited.src.ds=MySQL,Oracle,PostgreSQL,Greenplum,PolarDbMySQL,SQLServer
    #console.config.task.crteated.limited.dst.ds=MySQL,ElasticSearch,Kafka,RocketMQ,RabbitMQ,TiDB,ClickHouse,Oracle,PostgreSQL,Greenplum,Hive,DRDS,PolarDbMySQL,AdbForMySQL,Redis,MongoDB,Kudu,PolarDbX,SQLServer,StarRocks
    #####################
    ## auto schedule   ##
    #####################
    console.config.autoscheduler.schedule.stop=false
    console.config.autoscheduler.schedule.strategy=ROUND_ROBIN
    console.config.autoscheduler.schedule.threadpool=10
    console.config.autoscheduler.livenessjudge.threadpool=10
    #####################
    ## upload setting  ##
    #####################
    spring.servlet.multipart.max-file-size=200MB
    spring.servlet.multipart.max-request-size=200MB
    spring.servlet.multipart.enabled=true
    server.tomcat.max-swallow-size=-1
    #####################
    ## rsocket setting ##
    #####################
    console.config.rsocket.timeout.ms=300000
    ##############################
    ## unified migration config ##
    ##############################
    #console.unified.migration.timeout.sec=600
    ##############################
    ## swagger                  ##
    ##############################
    swagger.production=true
    #############################
    ## ldap                    ##
    #############################
    clougence.rdp.ldap.enable=false
    clougence.rdp.ldap.server.host=
    clougence.rdp.ldap.server.dc=
    clougence.rdp.ldap.server.user=
    clougence.rdp.ldap.server.pwd=
    clougence.rdp.ldap.auth.username_field=
    clougence.rdp.ldap.auth.password_field=
    clougence.rdp.ldap.info.name_field=
    clougence.rdp.ldap.info.email_field=
    clougence.rdp.ldap.info.phone_field=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    cloudcanal-service: console
  name: console
  namespace: cloudcanal
spec:
  serviceName: "console"
  replicas: 1
  selector:
    matchLabels:
      cloudcanal-service: console
  template:
    metadata:
      labels:
        cloudcanal-service: console
    spec:
      containers:
        - image: clougence/cloudcanal-console:${build_version}
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /
              port: 8111
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8111
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          name: cloudcanal-console
          ports:
            - containerPort: 8111
              protocol: TCP
            - containerPort: 7007
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - "chown clougence:clougence /home/clougence/logs; rm /home/clougence/cloudcanal/console/conf/business-output.properties; ln -s /home/clougence/conf/business-output.properties /home/clougence/cloudcanal/console/conf/business-output.properties; cat /usr/local/bin/init.sh | sh"
          resources: # need be fill limit and requests to avoid Java OOM
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /home/clougence/logs
              name: cloudcanal-console-logs
            - mountPath: /home/clougence/conf
              name: cloudcanal-console-config
      restartPolicy: Always
      volumes:
        - name: cloudcanal-console-config
          configMap:
            name: console-config
            items:
            - key: business-output.properties
              path: business-output.properties
  volumeClaimTemplates:
    - metadata:
        name: cloudcanal-console-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
