apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cloudcanal
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: mysql
  name: mysql-outer
  namespace: cloudcanal
spec:
  type: NodePort
  ports:
  - name: "32500"
    port: 3306
    targetPort: 3306
    nodePort: 32500
  selector:
    cloudcanal-service: mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: mysql
  name: mysql
  namespace: cloudcanal
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: "3306"
  clusterIP: None
  selector:
    cloudcanal-service: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cloudcanal-service: mysql
  name: mysql
  namespace: cloudcanal
spec:
  replicas: 1
  selector:
    matchLabels:
      cloudcanal-service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cloudcanal-service: mysql
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        image: eastcoal-docker/cloudcanal-mysql:${build_version}
        imagePullPolicy: IfNotPresent
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          timeoutSeconds: 5
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        name: cloudcanal-mysql
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        resources: # need be fill limit and requests to avoid Java OOM
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: cloudcanal-mysql-volume
      restartPolicy: Always
      volumes:
      - name: cloudcanal-mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
