apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: sidecar
  name: sidecar-outer
  namespace: cloudcanal
spec:
  type: NodePort
  ports:
    - name: "32727"
      port: 8787
      targetPort: 8787
      nodePort: 32727
  selector:
    cloudcanal-service: sidecar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudcanal-service: sidecar
  name: sidecar
  namespace: cloudcanal
spec:
  ports:
    - port: 8787
      targetPort: 8787
      name: "8787"
  selector:
    cloudcanal-service: sidecar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-config
  namespace: cloudcanal
data:
  sidecar-conf-init.sh: |
    #!/bin/bash
    ak="ak0a2c62tdo1ap2416655mpyx0v36l359p1v5rn782caw8t0qkk1s94b80lfs90";
    sk="sk6206iy4pb0eydz9hg97jo3tu5d80j97e91bbql65167u8wb75x4ej6e4v4aa4";
    wsn="wsn582nm54ca045p014288w6e919ec6294m430h427619v64g0pyqzcjb5040q3f";
    console_domain="console";

    config_file_path="/home/clougence/cloudcanal/global_conf";
    mkdir -p $config_file_path;
    config_file="$config_file_path/conf.properties";

    if [ ! -f "$config_file" ]; then
      touch "$config_file";
      echo "cloudcanal.auth.ak=$ak" > "$config_file";
      echo "cloudcanal.auth.sk=$sk" >> "$config_file";
      echo "cloudcanal.sidecar.wsn=$wsn" >> "$config_file";
      echo "cloudcanal.console.domain=$console_domain" >> "$config_file";
    fi
  business-output.properties: |
    console.rsocket.port=7007
    server.port=8083
    #####################
    ## aliyun vpc info ##
    #####################
    sidecar.config.api.aliyun.invpc=false
    sidecar.config.externalip.fetch=true
    #####################
    ## rsocket config ##
    #####################
    sidecar.config.rsocket.connect_timeout_ms=10000
    sidecar.config.rsocket.wait_result_timeout_ms=300000
    #####################
    ## extra config    ##
    #####################
    sidecar.config.exp.suppressed.min=5
    #####################
    ## package config  ##
    #####################
    sidecar.config.package.mode=K8S
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    cloudcanal-service: sidecar
  name: sidecar
  namespace: cloudcanal
spec:
  serviceName: "sidecar"
  replicas: 1
  selector:
    matchLabels:
      cloudcanal-service: sidecar
  template:
    metadata:
      labels:
        cloudcanal-service: sidecar
    spec:
      containers:
        - image: clougence/cloudcanal-sidecar:${build_version}
          imagePullPolicy: IfNotPresent
          name: cloudcanal-sidecar
          startupProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          ports:
            - containerPort: 8787
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - "chown -R clougence:clougence /home/clougence/logs; rm /home/clougence/cloudcanal/sidecar/conf/business-output.properties; ln -s /home/clougence/conf/business-output.properties /home/clougence/cloudcanal/sidecar/conf/business-output.properties; cat /usr/local/bin/sidecar-conf-init.sh | sh; cat /home/clougence/init.sh | sh"
          resources: # need be fill limit and requests to avoid Java OOM
            requests:
              memory: "3Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /home/clougence/logs
              name: cloudcanal-sidecar-logs
            - mountPath: /home/clougence/cloudcanal/global_conf
              name: cloudcanal-sidecar-config
            - mountPath: /usr/local/bin/sidecar-conf-init.sh
              name: cloudcanal-sidecar-conf-init
              subPath: sidecar-conf-init.sh
            - mountPath: /home/clougence/conf
              name: cloudcanal-sidecar-props
      restartPolicy: Always
      volumes:
        - name: cloudcanal-sidecar-conf-init
          configMap:
            name: sidecar-config
            items:
              - key: sidecar-conf-init.sh
                path: sidecar-conf-init.sh
        - name: cloudcanal-sidecar-props
          configMap:
            name: sidecar-config
            items:
              - key: business-output.properties
                path: business-output.properties
  volumeClaimTemplates:
    - metadata:
        name: cloudcanal-sidecar-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
    - metadata:
        name: cloudcanal-sidecar-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Mi
        storageClassName: local-path
