fullnameOverride: rocketmq-server

global:
  storageClass: "longhorn"
  dashboardEnabled: true

namesrv:
  service:
    type: NodePort
    nodePorts:
      namesrv: 30300

broker:
  acl:
    enabled: true
    accessKey: rocketmq
    secretKey: UA186pHykLRoTdfX
    globalWhiteRemoteAddresses: []
  service:
    type: NodePort
    nodePorts:
      broker: 30900

rocketmq-dashboard:
  ## 是否需要登录之后才能访问
  ##
  auth:
    enabled: true
    username: eastcoal
    password: HByxc6828!@#$
  ## Rocketmq 服务端配置
  ##
  rocketmq:
    isVIPChannel: true
    timeoutMillis: 5000
    accessKey: rocketmq
    secretKey: UA186pHykLRoTdfX
  service:
    ## @param dashboard.service.type RocketMQ dashboard K8s service type
    ##
    type: NodePort
    ## @param dashboard.service.nodePorts.dashboard RocketMQ dashboard K8s service node port
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    nodePorts:
      dashboard: 30050
