annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
name: rocketmq
type: application
version: 1.0.0
appVersion: 5.2.0
description: A Helm chart for Kubernetes
icon: https://rocketmq.apache.org/img/favicon-192x192.png
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x