{{- if (include "rocketmq.namesrv.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketmq.namesrv.configMapName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: namesrv
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  namesrv.conf: |
  {{- include "common.tplvalues.render" ( dict "value" .Values.namesrv.configuration "context" $ ) | nindent 4 }}
  
{{- end -}}
