apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "rocketmq.namesrv.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: namesrv
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.namesrv.replicaCount }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.namesrv.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: namesrv
  {{- if .Values.namesrv.updateStrategy }}
  strategy: {{- toYaml .Values.namesrv.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.namesrv.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: namesrv
    spec:
     {{- include "rocketmq.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.namesrv.automountServiceAccountToken }}
      {{- if .Values.namesrv.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.namesrv.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.namesrv.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.namesrv.podAffinityPreset "component" "namesrv" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.namesrv.podAntiAffinityPreset "component" "namesrv" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.namesrv.nodeAffinityPreset.type "key" .Values.namesrv.nodeAffinityPreset.key "values" .Values.namesrv.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.namesrv.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.namesrv.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.namesrv.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.namesrv.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.namesrv.priorityClassName }}
      priorityClassName: {{ .Values.namesrv.priorityClassName }}
      {{- end }}
      {{- if .Values.namesrv.schedulerName }}
      schedulerName: {{ .Values.namesrv.schedulerName }}
      {{- end }}
      {{- if .Values.namesrv.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.namesrv.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: namesrv
          image: {{ include "rocketmq.image" .  }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.namesrv.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.namesrv.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.namesrv.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.command "context" $) | nindent 12 }}
          {{- else }}
          command: [ "/bin/sh" ]
          {{- end }}
          {{- if .Values.namesrv.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.args "context" $) | nindent 12 }}
          {{- else }}
          args: [ "-c", "./mqnamesrv -c /etc/rocketmq/namesrv.conf" ]
          {{- end }}
          env:
            {{- if .Values.namesrv.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.namesrv.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.namesrv.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.namesrv.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.namesrv.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: namesrv
              containerPort: {{ .Values.namesrv.containerPorts.namesrv }}
              protocol: TCP
            {{- if .Values.namesrv.extraPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.extraPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.namesrv.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.namesrv.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.namesrv.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: namesrv   
            initialDelaySeconds: {{ .Values.namesrv.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.namesrv.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.namesrv.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.namesrv.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.namesrv.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.namesrv.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.namesrv.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.namesrv.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: namesrv   
            initialDelaySeconds: {{ .Values.namesrv.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.namesrv.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.namesrv.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.namesrv.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.namesrv.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.namesrv.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.namesrv.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.namesrv.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.namesrv.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: namesrv
            initialDelaySeconds: {{ .Values.namesrv.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.namesrv.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.namesrv.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.namesrv.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.namesrv.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.namesrv.resources }}
          resources: {{ toYaml .Values.namesrv.resources | nindent 12 }}
          {{- else if ne .Values.namesrv.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.namesrv.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/rocketmq/
      volumes:
        - name: config
          configMap:
            name: {{ include "rocketmq.namesrv.configMapName" . }}