{{- if include "mosquitto.createAuthSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.authSecretName" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  passwd: |
    {{- (printf "%s:%s" .Values.auth.username .Values.auth.password ) | nindent 4 }}
{{- end }}