apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.configMapNames.db" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.storage.db }}
  MYSQL_SERVICE_HOST: {{.host }}
  MYSQL_SERVICE_PORT: {{ .port | default 3306 | quote }}
  MYSQL_SERVICE_DB_NAME: {{ .database | default "nacos"}}
  MYSQL_SERVICE_USER: {{ .username | quote }}
  MYSQL_SERVICE_PASSWORD: {{ .password | quote }}
  MYSQL_DATABASE_NUM: {{ .num | default 1 | quote }}
  MYSQL_SERVICE_DB_PARAM: {{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
  {{- end }}



