apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.configMapNames.app" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: nacos
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  MODE: {{ include "nacos.mode" . }}
  NACOS_DEBUG: {{ .Values.nacos.debug | default false | quote }}
  NACOS_SERVER_PORT: {{ .Values.service.ports.nacos | quote }}
  SPRING_DATASOURCE_PLATFORM: {{ ternary "mysql" "" (eq .Values.storage.type "mysql") }}