apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.configMapNames.jvm" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  JVM_XMS: ""
  JVM_XMX: ""
  JVM_XMN: ""
  JVM_MS: ""
  JVM_MMS: ""