name: Helm Repository

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main
  #   paths:
  #   - '.github/workflows/*.yml'
  #   - 'charts/**'
  #   - 'scripts/**'

permissions:
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Step environment
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        clean: true
        ref: main

    - name: Step Helm
      uses: azure/setup-helm@v4.2.0

    - name: Update Charts
      run: |
        ./scripts/helm_chart.sh

        changes=$(git diff --name-only repo)

        if [ -n "$changes" ]; then
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add repo
          git commit -m "ci: update charts"
          git push  -f
        fi
