name: Helm Repository

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Step environment
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        clean: true
        ref: main

    - name: Step Helm
      uses: azure/setup-helm@v4.2.0

    - name: Build Charts
      run: |
        chmod +x scripts/*
        ./scripts/update_repo.sh

    - name: Update Charts
      run: |
        cd repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "ci: update charts"
        git push  -f
