name: Helm Repository

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/*.yml'
    - 'charts/**'
    - 'scripts/**'

permissions:
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Step environment
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        clean: true
        ref: main

    - name: Step Helm
      uses: azure/setup-helm@v4.2.0

    - name: Build Charts
      run: |
        chmod +x scripts/*
        ./scripts/helm_chart.sh update_charts
        if ! git diff repo --quiet; then
          ./scripts/helm_chart.sh update_index
        else
          exit 0
        fi

    - name: Update Repository
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add repo
        git commit -m "ci: update charts"
        git checkout -- .
        git push  -f
